// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiYaTpS7dGB-QvF_TF5RzNEvX51jUl_8I',
    appId: '1:796386447489:web:8db5a40e5cdfb805f57d80',
    messagingSenderId: '796386447489',
    projectId: 'fir-tutorial-65078',
    authDomain: 'fir-tutorial-65078.firebaseapp.com',
    storageBucket: 'fir-tutorial-65078.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bWEiCNziJdCciqiea-m4K4h7GBPhZhk',
    appId: '1:796386447489:android:682bb0a3993c6a19f57d80',
    messagingSenderId: '796386447489',
    projectId: 'fir-tutorial-65078',
    storageBucket: 'fir-tutorial-65078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe7z6gPlOFt-0-TvV342StfFAio8c4Azg',
    appId: '1:796386447489:ios:2cd4720b3d700702f57d80',
    messagingSenderId: '796386447489',
    projectId: 'fir-tutorial-65078',
    storageBucket: 'fir-tutorial-65078.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe7z6gPlOFt-0-TvV342StfFAio8c4Azg',
    appId: '1:796386447489:ios:2cd4720b3d700702f57d80',
    messagingSenderId: '796386447489',
    projectId: 'fir-tutorial-65078',
    storageBucket: 'fir-tutorial-65078.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiYaTpS7dGB-QvF_TF5RzNEvX51jUl_8I',
    appId: '1:796386447489:web:57e77a061b612d72f57d80',
    messagingSenderId: '796386447489',
    projectId: 'fir-tutorial-65078',
    authDomain: 'fir-tutorial-65078.firebaseapp.com',
    storageBucket: 'fir-tutorial-65078.firebasestorage.app',
  );
}
